id: opecha:P000540
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4051
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་གྱི་དབུ་ཚལ་དྲི་མའི་འཇིགས་སྐྱོབ།
  volume:
    16e447edde964f41860b6e4cc4f71a71:
      image_group_id: I3CN4238
      title: Volume 1 of zab chos zhi khro dgongs pa rang grol gyi dbu tshal dri ma'i
        'jigs skyob/
      volume_number: 1
      total_pages: 1066
  author: ''
ebook_metadata:
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་གྱི་དབུ་ཚལ་དྲི་མའི་འཇིགས་སྐྱོབ།
  author: ''
  sku: P000540
  cover: cover.jpg
  layers:
  - pagination
